# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='username',
        ),
    ]
