# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hiredate',
            field=models.DateTimeField(null=True),
        ),
    ]
