# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0003_users_bdate'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ManyToManyField(related_name='userItems', to='loginReg.Users'),
        ),
    ]
