# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_products_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='item',
            new_name='name',
        ),
    ]
